#!/bin/bash

# Some video generated by GPT-4 may not look so good,
# Or depict humans in an inappropriate way

echo "removing inappropriate videos.."
rm -f $WEBTV_VIDEO_STORAGE_PATH_CHANNEL_2*2f6806a9-5cee-4892-adba-83548122309f*
rm -f $WEBTV_VIDEO_STORAGE_PATH_CHANNEL_2*6741315d-9b5e-43ef-ab6d-e14e6f93897a*
rm -f $WEBTV_VIDEO_STORAGE_PATH_CHANNEL_2*e756d6ea-c424-4a05-b553-4be80ec68513*
rm -f $WEBTV_VIDEO_STORAGE_PATH_CHANNEL_2*d6bb4dcf-65ce-4e73-b39d-e5f6d58001fc*